version: '2.1'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: ruby:2.3.3-alpine
    volumes:
      - bundle-data:/bundle
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
