version: '3.3'

services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    volumes:
      - ./src:/work/app
      - bundle-data:/bundle
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
